# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#
# Project Euler - Problem 2
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

from decimal import *
import time
getcontext().prec = 3
start = time.clock()

a = 0
b = 1
fib = a + b

total = 0
while fib < 4e6:
	if not fib % 2:
		total += fib
	a = b
	b = fib
	fib = a + b
end = time.clock()
print(total)
print('Processing Time:', Decimal(end) - Decimal(start), 'seconds')

